// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.m20.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.EntersWithDynamicCounters
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Squad Captain
 * {4}{W}
 * Creature — Human Soldier
 * 2/2
 * Vigilance (Attacking doesn't cause this creature to tap.)
 * This creature enters with a +1/+1 counter on it for each other creature you control.
 */
val SquadCaptain = card("Squad Captain") {
    manaCost = "{4}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Human Soldier"
    oracleText = "Vigilance (Attacking doesn't cause this creature to tap.)\nThis creature enters with a +1/+1 counter on it for each other creature you control."
    power = 2
    toughness = 2
    keywords(Keyword.VIGILANCE)
    replacementEffect(
        EntersWithDynamicCounters(
            count = DynamicAmount.AggregateBattlefield(Player.You, GameObjectFilter.Creature.attacking())
        )
    )
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "38"
        artist = "Cristi Balanescu"
        flavorText = "The strength of the one is the strength of the many."
        imageUri = "https://cards.scryfall.io/normal/front/b/d/bd7d6112-ffb2-41d8-98ed-1a7b22841dfd.jpg"
    }
}
