// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CounterEffect
import com.wingedsheep.sdk.scripting.targets.TargetSpell


/**
 * Blue Elemental Blast
 * {U}
 * Instant
 * Choose one —
 * • Counter target red spell.
 * • Destroy target red permanent.
 */
val BlueElementalBlast = card("Blue Elemental Blast") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Choose one —\n• Counter target red spell.\n• Destroy target red permanent."
    spell {
        val t = target("target", TargetSpell())
        effect = CounterEffect()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "49"
        artist = "Richard Thomas"
        imageUri = "https://cards.scryfall.io/normal/front/2/0/20d666ef-39bf-4fbf-8201-5f1056539da2.jpg"
    }
}
