// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.ForEachPlayerEffect
import com.wingedsheep.sdk.scripting.effects.ForEachTargetEffect
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.targets.TargetPermanent
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Volcanic Eruption
 * {X}{U}{U}{U}
 * Sorcery
 * Destroy X target Mountains. Volcanic Eruption deals damage to each creature and each player equal to the number of Mountains put into a graveyard this way.
 */
val VolcanicEruption = card("Volcanic Eruption") {
    manaCost = "{X}{U}{U}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Destroy X target Mountains. Volcanic Eruption deals damage to each creature and each player equal to the number of Mountains put into a graveyard this way."
    spell {
        val t = target("target", TargetPermanent())
        effect = Effects.Composite(
            ForEachTargetEffect(
                listOf(Effects.Move(EffectTarget.ContextTarget(0), Zone.GRAVEYARD, byDestruction = true))
            ),
            Effects.Composite(
                Effects.ForEachInGroup(
                    GroupFilter(GameObjectFilter.Land.withSubtype(Subtype.MOUNTAIN)),
                    DealDamageEffect(
                        DynamicAmount.AggregateBattlefield(
                            Player.You,
                            GameObjectFilter.Land.withSubtype(Subtype.MOUNTAIN)
                        ),
                        EffectTarget.Self
                    )
                ),
                ForEachPlayerEffect(
                    Player.Each,
                    listOf(
                        DealDamageEffect(
                            DynamicAmount.AggregateBattlefield(
                                Player.You,
                                GameObjectFilter.Land.withSubtype(Subtype.MOUNTAIN)
                            ),
                            EffectTarget.Controller
                        )
                    )
                )
            )
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "88"
        artist = "Douglas Shuler"
        imageUri = "https://cards.scryfall.io/normal/front/a/8/a80582b1-09db-45f8-b362-0e5207a5a8e6.jpg"
    }
}
