-- Initial schema for accounts, server-side decks, and match-history stats.
--
-- This migration only runs when accounts are enabled (`accounts.enabled=true`, which lets the
-- DataSource + Flyway auto-config activate). Hot game/lobby/tournament state is NOT stored here —
-- that stays in Redis / in-memory. Postgres is only for durable, user-owned data.

-- Accounts. Identity is the email; display_name is shown in the UI and defaults to the email
-- local-part on first login. Magic-link login means we never store a password.
CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        TEXT        NOT NULL UNIQUE,
    display_name TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Single-use, short-lived magic-link tokens. We store only the SHA-256 hash of the raw token
-- (the raw value lives only in the emailed link), so a DB leak can't be replayed into a login.
CREATE TABLE login_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  TEXT        NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_login_tokens_user ON login_tokens (user_id);

-- Saved decks. `data` holds the full deck JSON (the client's SharedDeck shape: card-name -> count,
-- optional per-card printing pins, commander, etc.); `name`/`format` are denormalized for cheap
-- list views without parsing the JSON.
CREATE TABLE decks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    format     TEXT,
    data       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_decks_user ON decks (user_id);

-- One row per finished game with meaningful activity. Stats are computed as queries over the
-- participants table; there is deliberately no denormalized per-user stats table yet.
CREATE TABLE match_results (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         TEXT        NOT NULL,
    format          TEXT,
    tournament_name TEXT,
    started_at      TIMESTAMPTZ,
    ended_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_match_results_game ON match_results (game_id);

-- A seat in a finished game. user_id is null for guests and AI; player_name is always captured so
-- guest/AI games still render in history.
CREATE TABLE match_participants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id    BIGINT  NOT NULL REFERENCES match_results (id) ON DELETE CASCADE,
    user_id     BIGINT  REFERENCES users (id) ON DELETE SET NULL,
    player_name TEXT    NOT NULL,
    won         BOOLEAN NOT NULL
);
CREATE INDEX idx_match_participants_match ON match_participants (match_id);
CREATE INDEX idx_match_participants_user ON match_participants (user_id);
