// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.cmr.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Annoyed Altisaur
 * {5}{G}{G}
 * Creature — Dinosaur
 * 6/5
 * Reach, trample
 * Cascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order.)
 */
val AnnoyedAltisaur = card("Annoyed Altisaur") {
    manaCost = "{5}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Dinosaur"
    oracleText = "Reach, trample\nCascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order.)"
    power = 6
    toughness = 5
    keywords(Keyword.REACH, Keyword.TRAMPLE, Keyword.CASCADE)
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "216"
        artist = "Lars Grant-West"
        flavorText = "It pairs a long neck with a short temper."
        imageUri = "https://cards.scryfall.io/normal/front/7/5/7536d618-0c98-45bb-913b-b8117b4acf87.jpg"
    }
}
