// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.atq.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Shatterstorm
 * {2}{R}{R}
 * Sorcery
 * Destroy all artifacts. They can't be regenerated.
 */
val Shatterstorm = card("Shatterstorm") {
    manaCost = "{2}{R}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Destroy all artifacts. They can't be regenerated."
    spell {
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Artifact),
            Effects.Move(EffectTarget.Self, Zone.GRAVEYARD, byDestruction = true),
            noRegenerate = true
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "28"
        artist = "Mark Poole"
        flavorText = "Chains of leaping fire and sizzling lightning laid waste the artificers' handiwork, sparing not a single device."
        imageUri = "https://cards.scryfall.io/normal/front/0/9/0987461a-45c0-4956-8627-cd27a7e038d0.jpg"
    }
}
